[package]
name = "shorelark_server"
version = "0.1.1"
authors = ["Alexx Roche <notice-dev@alexx.net>"]
edition = "2018"

[dependencies]
actix-web = "2.0"
actix-rt = "1.1"
actix-files = "0.2.2"
env_logger = "0.8"
